export const dynamic = "force-dynamic";

interface HealthResponse {
  status: string;
  database: string;
  timestamp: string;
}

async function getHealth(): Promise<HealthResponse> {
  const apiBaseUrl = process.env.API_BASE_URL;

  if (!apiBaseUrl) {
    throw new Error("API_BASE_URL is not configured.");
  }

  const response = await fetch(`${apiBaseUrl}/api/health`, {
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(`API health request failed with status ${response.status}.`);
  }

  return response.json() as Promise<HealthResponse>;
}

export default async function HomePage() {
  const health = await getHealth();

  return (
    <main>
      <h1>__PROJECT_DISPLAY_NAME__</h1>
      <p>Generated by Agency CLI.</p>
      <p>API status: {health.status}</p>
      <p>Database status: {health.database}</p>
      <p>API timestamp: {health.timestamp}</p>
    </main>
  );
}